### ISSUE TITLE
Not compatible with newer (v2+) versions of log4js

### ISSUE THREAD

**Issue by Calvin445** [lajonat/log4js-appender-ratelimit-filter#2]
Syntax for config objects and the the interface for custom appenders has changed since v2. Functions to programmatically modify the config have also been removed. See https://log4js-node.github.io/log4js-node/migration-guide.html

PR to add support for v2+ and use newer versions of log4js https://github.com/lajonat/log4js-appender-ratelimit-filter/pull/1

**Comment by lajonat** [comment]
Thanks for the PR.

**Comment by Calvin445** [comment]
Will you release this version to npm?

**Comment by lajonat** [comment]
Should be updated now.

**Comment by Calvin445** [comment]
Thanks. Not an issue, but I'm curious why it's version 3.0.0 and not 2.0.0?

**Comment by lajonat** [comment]
Not sure, I think npm publish bumped it another version, but I didn't have the time to investigate it further, and I didn't want to roll it back.
